import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { NavigationBar } from "@/components/navigation-bar";
import { ThemeToggle } from "@/components/theme-toggle";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div
            className="h-screen overflow-hidden flex flex-col items-center bg-white font-sans dark:bg-black"
            style={{
              backgroundImage:
                "radial-gradient(circle, rgb(174, 181, 191) 1.5px, transparent 1.5px)",
              backgroundSize: "24px 24px",
            }}
          >
            {/* Navigation Bar */}
            <NavigationBar />

            {/* Theme Toggle */}
            <div className="fixed top-2 right-2 z-50">
              <div className="bg-rose-50/40 backdrop-blur-[1px] border-rose-300 border-2 p-0.5 rounded-full">
                <ThemeToggle />
              </div>
            </div>

            {/* Header Spacer */}
            <div className="h-14 w-full flex-shrink-0" />

            {/* Page Content */}
            <div className="w-full overflow-hidden" style={{ height: 'calc(100vh - 3.5rem)' }}>
              {children}
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
